### ISSUE TITLE
New version of PSPDFKit has PSPDFKit.framework instead of PSPDFKit.embeddedframework

### ISSUE THREAD

**Issue by g41n** [PSPDFKit/Appcelerator-iOS#10]
Hello, I'm trying to compile the Appcelerator Bridge with PSPDFKit 5.1.1 following the README, but when it says to copy `PSPDFKit.embeddedframework` I can see only the `PSPDFKit.framework` file in my package.

After many tries I've managed to compile with this additional steps (the checkout of the project is in `/Users/myuser/pspdfkit/Appcelerator-iOS`) :
* configure `titanium.xcconfig` with my TITANIUM_SDK_VERSION, that is 5.2.0.v20151210082902
* create the directory `PSPDFKit.embeddedframework` in the root of the checkout project
* copy `PSPDFKit.framework` into the `PSPDFKit.embeddedframework` directory previously created
* create this link with these commands, otherwise the build fails

 $ mkdir -p /Users/myuser/pspdfkit/Appcelerator-iOS/PSPDFKit.embeddedframework/PSPDFKit.framework/Versions/A
 $ ln -s /Users/myuser/pspdfkit/Appcelerator-iOS/PSPDFKit.embeddedframework/PSPDFKit.framework/PSPDFKit /Users/myuser/pspdfkit/Appcelerator-iOS/PSPDFKit.embeddedframework/PSPDFKit.framework/Versions/A/PSPDFKit

Anyway, even if the module build succeeded, the build with Appcelerator fails with this error:
 [ERROR] :  ** BUILD FAILED **
 [ERROR] :  The following build commands failed:
 [ERROR] :  	Ld build/Intermediates/myapp.build/Debug-iphonesimulator/myapp.build/Objects-normal/x86_64/myapp normal x86_64
 [ERROR] :  (1 failure)
 2016-01-12T15:47:55.224Z | TRACE  | titanium exited with exit code 1
 2016-01-12T15:47:55.225Z | ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/myuser/.appcelerator/install/5.1.0/package/node_modules/appc-cli-titanium/plugins/run.js:92:66)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
 2016-01-12T15:47:55.226Z | TRACE  | Sending exit signal to titanium process:  42941

Any help would be appreciated.
Thanks in advance.

**Comment by steipete** [comment]
See the note in our readme:

>Note: Currently Appcelerator does not work with dynamic frameworks. As of PSPDFKit v5, we only provide a dynamic framework. We still keep the wrapper open source, and can provide a static build on request until Appcelerator resolves this issue. We're already in contact with them and are helping them to find a solution.

Until Appcelerator has resolved this, we can send you a copy of an internal build. We still keep the repository open source since we hope that Appcelerator soon fixes this issue - after all dynamic frameworks were introduced in iOS 8, which is a while ago.

I'm closing this ticket. Can you ping us at https://pspdfkit.com/support/request so we can send you a copy of the precompiled SDK?

**Comment by juliangrosshauser** [comment]
Since a few versions ago our Appcelerator bindings are now building with the dynamic `PSPDFKit.framework`. Please take a look at the README for build instructions.
