### ISSUE TITLE
Build 9.0.2 for iOS 13

### ISSUE THREAD

**Issue by brownemint** [PSPDFKit/Appcelerator-iOS#29]
I'm trying to build 9.0.2 into a Ti module for iOS.

I've followed the following instructions:

> 1. Checkout the project: git clone https://github.com/PSPDFKit/Appcelerator-iOS.git
> 2. Make sure you have Titanium 8.0.1.GA or later installed: https://www.appcelerator.com or ti sdk install 8.0.1.GA
> 3. Download the binary build of PSPDFKit from your customer portal
> 4.  Open the downloaded .dmg and copy PSPDFKit.framework and PSPDFKitUI.framework into the platform/ folder inside the project. 4a. Optionally, copy the PSPDFKit.bundle from PSPDFKit.framework to Resources/
> 5. Call ti build -p ios --build-only in the Appcelerator-iOS folder.

For part 4, I'm using the PSPDFKit.framework and PSPDFKitUI.framework found in $SRC_ROOT/platform⁩/⁨PSPDFKit.xcframework⁩/⁨ios-arm64 and ⁩$SRC_ROOT/platform⁩/⁨PSPDFKitUI.xcframework⁩/⁨ios-arm64 respectively.

I came across the 'PSPDFKit.h' file not found issue, so did the following:
> If PSPDFKit.h can't be found you need to add the directory that contains PSPDFKit.h to the "Header Search Paths" build setting in the Xcode project (PSPDFKit-Titanium.xcodeproj). The correct directories are $(SRCROOT)/PSPDFKit.framework/Headers and $(SRCROOT)/PSPDFKitUI.framework/Headers (recursive).

Now I'm stuck with the following:

>The following build commands failed:
>[ERROR] [xcode-sim] 	CompileC build/PSPDFKit-Titanium.build/Release-iphonesimulator/pspdfkit.build/Objects-normal/x86_64/ComPspdfkitModule.o Classes/ComPspdfkitModule.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

My System is:

```
Operating System
  Name                        = Mac OS X
  Version                     = 10.14.5
  Architecture                = 64bit
  # CPUs                      = 8
  Memory                      = 16.0GB

Node.js
  Node.js Version             = 10.13.0
  npm Version                 = 6.12.0

Titanium CLI
  CLI Version                 = 5.2.2
  node-appc Version           = 0.2.49

Titanium SDKs
  8.3.0.v20191022124857
    Version                   = 8.3.0
    Install Location          = /Users/brownemt/Library/Application Support/Titanium/mobilesdk/osx/8.3.0.v20191022124857
    Platforms                 = iphone, android
    git Hash                  = e679a65674
    git Timestamp             = 10/22/2019 19:54
    node-appc Version         = 0.3.4
  8.2.0.GA
    Version                   = 8.2.0
    Install Location          = /Users/brownemt/Library/Application Support/Titanium/mobilesdk/osx/8.2.0.GA
    Platforms                 = iphone, android
    git Hash                  = 6bfdf6e394
    git Timestamp             = 9/17/2019 17:13
    node-appc Version         = 0.3.4
  8.0.1.GA
    Version                   = 8.0.1
    Install Location          = /Users/brownemt/Library/Application Support/Titanium/mobilesdk/osx/8.0.1.GA
    Platforms                 = iphone, android
    git Hash                  = c4f6f25c7d
    git Timestamp             = unknown
    node-appc Version         = 0.2.47
Xcode
  11.1 (build 11A1027) - Xcode default
    Install Location          = /Applications/Xcode.app/Contents/Developer
    iOS SDKs                  = 13.1
    iOS Simulators            = 13.1
    Watch SDKs                = 6.0
    Watch Simulators          = 6.0
    Supported by TiSDK 8.0.1.GA = yes
    EULA Accepted             = yes
    Teams                     = none
```

Any thoughts on what the issue is and how I can build the module? The readme seems to focus on PSPDFKit 8, whereas I'm using PSPDFKit 9 (as provided by my customer), so is there a difference in building the module between the 2 releases?

**Comment by OscarSwanros** [comment]
@brownemint — thanks for the report! I've opened a PR to address this and update the wrapper so you can integrate it correctly. It'll be merged soon.

Thanks!

**Comment by OscarSwanros** [comment]
@brownemint — https://github.com/PSPDFKit/Appcelerator-iOS/pull/30 is now merged, and you can now take a look at the updated README and update to correctly integrate PSPDFKit into your project.

Thanks!
